
name: CI

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: self-hosted
    steps:
     - name: Check out the repo
       uses: actions/checkout@v2
     - name: Set Relase version
       id: vars
       run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
     - name: build docker image and push to ecr repo
       run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 362520992479.dkr.ecr.us-east-1.amazonaws.com
          docker build -t nodeapp .
          docker tag nodeapp:latest 362520992479.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest
          docker push 362520992479.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest
       env:
          AWS_ACCESS_KEY_ID: AKIAVIZ7PLLP3CVG3L7R
          AWS_SECRET_ACCESS_KEY:  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
          AWS_REGION: us-east-1
          
     - name: Check tag version
       run: | 
           echo $RELEASE_VERSION
           echo ${{ env.RELEASE_VERSION }}
           echo "AKIAVIZ7PLLP3CVG3L7R" >> $GITHUB_ENV
           echo "8VGg99KI1hGKmZqEWdDs7Ak9UZlZt1/FlqMV/Djq" >> $GITHUB_ENV
     - name: terraform initialization 
       run: cd terraform_code/ && terraform init 
     - name: terraform deployment
       run: cd terraform_code/ && terraform apply -var="tag=${{ env.RELEASE_VERSION }}"  -auto-approve

     
